#环境配置
server:
  port: 10086


spring:

  #多环境配置
  profiles:
    active:
  #配置数据源信息
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
      username: root
      password: brozer
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/springboot_slave?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
      username: root
      password: brozer
      driver-class-name: com.mysql.jdbc.Driver

  #spring-data-jpa配置
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        show_sql: true

  #Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8 #连接池最大连接数
      max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 #连接池中最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
    timeout: 0  #连接超时时间

  #thymeleaf模板引擎配置
  thymeleaf:
    suffix: .html

  #多彩输出
  output:
    ansi:
      enabled: detect
  mail:
    host: smtp.163.com
    username: Lixuanshengchao@163.com
    password: qwQWqwQW
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
##日志配置
#logging:
#  #文件输出
#  file: my.log
#  level: debug
#  #级别控制



#自定义属性配置
custom.config.siteName: www.axht.trade-author<${custom.config.author}>  #站点名称
custom.config.author: brozer



